../run_gem5_alpha_spec06_benchmark.sh -b "perlbench\;sjeng" -o ~/fc_70/perlbench_sjeng -s --smt -v fast -a ALPHA_FC
../run_gem5_alpha_spec06_benchmark.sh -b "gcc\;bzip2" -o ~/fc_70/gcc_bzip2 -s --smt -v fast -a ALPHA_FC
../run_gem5_alpha_spec06_benchmark.sh -b "libquantum\;libquantum" -o ~/fc_70/libquantum_libquantum -s --smt -v fast -a ALPHA_FC
../run_gem5_alpha_spec06_benchmark.sh -b "gobmk\;libquantum" -o ~/fc_70/gobmk_libquantum -s --smt -v fast -a ALPHA_FC
../run_gem5_alpha_spec06_benchmark.sh -b "perlbench\;bzip2" -o ~/fc_70/perlbench_bzip2 -s --smt -v fast -a ALPHA_FC
../run_gem5_alpha_spec06_benchmark.sh -b "libquantum\;astar" -o ~/fc_70/libquantum_astar -s --smt -v fast -a ALPHA_FC
../run_gem5_alpha_spec06_benchmark.sh -b "bzip2\;libquantum" -o ~/fc_70/bzip2_libquantum -s --smt -v fast -a ALPHA_FC
../run_gem5_alpha_spec06_benchmark.sh -b "hmmer\;gobmk" -o ~/fc_70/hmmer_gobmk -s --smt -v fast -a ALPHA_FC
../run_gem5_alpha_spec06_benchmark.sh -b "mcf\;astar" -o ~/fc_70/mcf_astar -s --smt -v fast -a ALPHA_FC
../run_gem5_alpha_spec06_benchmark.sh -b "gcc\;libquantum" -o ~/fc_70/gcc_libquantum -s --smt -v fast -a ALPHA_FC
../run_gem5_alpha_spec06_benchmark.sh -b "hmmer\;astar" -o ~/fc_70/hmmer_astar -s --smt -v fast -a ALPHA_FC
../run_gem5_alpha_spec06_benchmark.sh -b "gobmk\;sjeng" -o ~/fc_70/gobmk_sjeng -s --smt -v fast -a ALPHA_FC
