../run_gem5_alpha_spec06_benchmark.sh -b "perlbench\;sjeng" -o ~/dyn_96_SQ/perlbench_sjeng -s --smt -v fast -a ALPHA_CC
../run_gem5_alpha_spec06_benchmark.sh -b "gcc\;bzip2" -o ~/dyn_96_SQ/gcc_bzip2 -s --smt -v fast -a ALPHA_CC
../run_gem5_alpha_spec06_benchmark.sh -b "libquantum\;libquantum" -o ~/dyn_96_SQ/libquantum_libquantum -s --smt -v fast -a ALPHA_CC
../run_gem5_alpha_spec06_benchmark.sh -b "gobmk\;libquantum" -o ~/dyn_96_SQ/gobmk_libquantum -s --smt -v fast -a ALPHA_CC
../run_gem5_alpha_spec06_benchmark.sh -b "perlbench\;bzip2" -o ~/dyn_96_SQ/perlbench_bzip2 -s --smt -v fast -a ALPHA_CC
../run_gem5_alpha_spec06_benchmark.sh -b "libquantum\;astar" -o ~/dyn_96_SQ/libquantum_astar -s --smt -v fast -a ALPHA_CC
../run_gem5_alpha_spec06_benchmark.sh -b "bzip2\;libquantum" -o ~/dyn_96_SQ/bzip2_libquantum -s --smt -v fast -a ALPHA_CC
../run_gem5_alpha_spec06_benchmark.sh -b "hmmer\;gobmk" -o ~/dyn_96_SQ/hmmer_gobmk -s --smt -v fast -a ALPHA_CC
../run_gem5_alpha_spec06_benchmark.sh -b "mcf\;astar" -o ~/dyn_96_SQ/mcf_astar -s --smt -v fast -a ALPHA_CC
../run_gem5_alpha_spec06_benchmark.sh -b "gcc\;libquantum" -o ~/dyn_96_SQ/gcc_libquantum -s --smt -v fast -a ALPHA_CC
../run_gem5_alpha_spec06_benchmark.sh -b "hmmer\;astar" -o ~/dyn_96_SQ/hmmer_astar -s --smt -v fast -a ALPHA_CC
../run_gem5_alpha_spec06_benchmark.sh -b "gobmk\;sjeng" -o ~/dyn_96_SQ/gobmk_sjeng -s --smt -v fast -a ALPHA_CC
